// Copyright 2026 Reflective Labs
// SPDX-License-Identifier: MIT

//! `quality-render` — read `arena-tests/reports/history.jsonl` and
//! regenerate `atelier-showcase/quality/dashboard.md`.
//!
//! The dashboard is a human-readable snapshot:
//!
//! - **Current verdicts**: latest run's per-dimension verdict + score.
//! - **Trends**: last N runs of each dimension, glyph-coded.
//! - **Recent findings**: top-severity findings from the latest run.
//!
//! Invariants:
//! - This binary never modifies `history.jsonl` — strictly read-only.
//! - `dashboard.md` is auto-generated. The file carries a "do not
//!   edit by hand" banner.
//! - If history is empty, the dashboard says so honestly; it doesn't
//!   fabricate trends.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::Deserialize;

/// One run, deserialized loosely from arena-driver's report shape.
#[derive(Debug, Deserialize)]
struct Report {
    timestamp: chrono::DateTime<chrono::Utc>,
    aggregate_verdict: String,
    aggregate_score: Option<u8>,
    dimensions: Vec<DimensionResult>,
}

#[derive(Debug, Deserialize)]
struct DimensionResult {
    id: String,
    #[allow(dead_code)]
    name: String,
    recurring_property: String,
    verdict: String,
    score: Option<u8>,
    findings: Vec<Finding>,
    duration_ms: u64,
}

#[derive(Debug, Deserialize)]
struct Finding {
    title: String,
    severity: String,
    evidence: String,
    #[allow(dead_code)]
    recurring_property: Option<String>,
}

fn main() -> Result<()> {
    let workspace_root = locate_workspace_root()?;
    let history_path = workspace_root.join("arena-tests/reports/history.jsonl");
    let dashboard_path = workspace_root.join("atelier-showcase/quality/dashboard.md");

    let runs =
        read_history(&history_path).with_context(|| format!("read {}", history_path.display()))?;

    let rendered = render_dashboard(&runs);
    std::fs::write(&dashboard_path, rendered)
        .with_context(|| format!("write {}", dashboard_path.display()))?;

    println!(
        "quality-render: regenerated {} from {} run(s) in {}",
        dashboard_path.display(),
        runs.len(),
        history_path.display(),
    );
    Ok(())
}

fn locate_workspace_root() -> Result<PathBuf> {
    let mut dir = std::env::current_dir().context("current dir")?;
    loop {
        if dir.join("MASTERPLAN.md").exists() && dir.join("KB").exists() {
            return Ok(dir);
        }
        match dir.parent() {
            Some(parent) => dir = parent.to_path_buf(),
            None => anyhow::bail!(
                "could not locate reflective workspace root \
                 (looked for MASTERPLAN.md + KB/ walking up from cwd)"
            ),
        }
    }
}

fn read_history(path: &Path) -> Result<Vec<Report>> {
    if !path.exists() {
        return Ok(Vec::new());
    }
    let content = std::fs::read_to_string(path)?;
    let mut runs = Vec::new();
    for (i, line) in content.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        let run: Report = serde_json::from_str(line)
            .with_context(|| format!("parse history.jsonl line {}", i + 1))?;
        runs.push(run);
    }
    Ok(runs)
}

fn render_dashboard(runs: &[Report]) -> String {
    use std::fmt::Write;
    let mut s = String::new();

    writeln!(s, "---").unwrap();
    writeln!(s, "tags: [quality, dashboard, atelier, generated]").unwrap();
    writeln!(s, "generated-by: atelier-showcase/crates/quality-render").unwrap();
    writeln!(s, "source: derived").unwrap();
    writeln!(s, "---").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "# Quality dashboard").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "> **Auto-generated.** Do not edit this file by hand.").unwrap();
    writeln!(s, ">").unwrap();
    writeln!(
        s,
        "> Regenerate with `just render-dashboard` (or `cargo run -p quality-render`)."
    )
    .unwrap();
    writeln!(s).unwrap();

    if runs.is_empty() {
        writeln!(
            s,
            "_No arena runs recorded yet. Run `cd arena-tests && just report-write` \
             to produce the first entry._"
        )
        .unwrap();
        return s;
    }

    let latest = runs.last().expect("non-empty checked above");
    writeln!(s, "## Latest run").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "- **When**: {}", latest.timestamp.to_rfc3339()).unwrap();
    writeln!(
        s,
        "- **Aggregate verdict**: **{}**",
        latest.aggregate_verdict
    )
    .unwrap();
    if let Some(score) = latest.aggregate_score {
        writeln!(
            s,
            "- **Aggregate score**: **{score}/100** (minimum across dimensions, not average)"
        )
        .unwrap();
    } else {
        writeln!(
            s,
            "- **Aggregate score**: — (no dimension produced a numeric score)"
        )
        .unwrap();
    }
    writeln!(s, "- **Total runs in history**: {}", runs.len()).unwrap();
    writeln!(s).unwrap();

    writeln!(s, "## Per-dimension snapshot").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "| Dimension | Verdict | Score | Property | Duration |").unwrap();
    writeln!(s, "|---|---|---|---|---|").unwrap();
    for d in &latest.dimensions {
        let score = d
            .score
            .map_or_else(|| "—".to_string(), |v| format!("{v}/100"));
        writeln!(
            s,
            "| [`{}`](dimensions/{}.md) | **{}** | {} | [`{}`](properties/{}.md) | {} ms |",
            d.id, d.id, d.verdict, score, d.recurring_property, d.recurring_property, d.duration_ms,
        )
        .unwrap();
    }
    writeln!(s).unwrap();

    if runs.len() > 1 {
        writeln!(s, "## Trend (last {} runs)", runs.len().min(10)).unwrap();
        writeln!(s).unwrap();
        writeln!(
            s,
            "Each row is one dimension. Each glyph is one run, oldest → newest."
        )
        .unwrap();
        writeln!(s, "`P` Pass · `W` Warn · `F` Fail · `S` Skip · `E` Error").unwrap();
        writeln!(s).unwrap();
        writeln!(s, "```text").unwrap();
        let recent: Vec<&Report> = runs.iter().rev().take(10).rev().collect();
        let dim_ids: Vec<String> = latest.dimensions.iter().map(|d| d.id.clone()).collect();
        let widest = dim_ids.iter().map(String::len).max().unwrap_or(0);
        for id in &dim_ids {
            let row: String = recent
                .iter()
                .map(|r| {
                    r.dimensions
                        .iter()
                        .find(|d| &d.id == id)
                        .map_or(' ', |d| verdict_glyph(&d.verdict))
                })
                .collect();
            writeln!(s, "{id:<width$}  {row}", width = widest).unwrap();
        }
        writeln!(s, "```").unwrap();
        writeln!(s).unwrap();
    }

    writeln!(s, "## Findings from the latest run").unwrap();
    writeln!(s).unwrap();
    let mut emitted_any = false;
    for severity in &["critical", "high", "moderate", "info"] {
        let matches: Vec<(&str, &Finding)> = latest
            .dimensions
            .iter()
            .flat_map(|d| {
                d.findings
                    .iter()
                    .filter(|f| f.severity == *severity)
                    .map(move |f| (d.id.as_str(), f))
            })
            .collect();
        if matches.is_empty() {
            continue;
        }
        emitted_any = true;
        writeln!(s, "### {} severity", titlecase(severity)).unwrap();
        writeln!(s).unwrap();
        for (dim, f) in matches {
            writeln!(s, "- **[{dim}] {}**", f.title).unwrap();
            writeln!(s, "  - {}", f.evidence).unwrap();
        }
        writeln!(s).unwrap();
    }
    if !emitted_any {
        writeln!(s, "_No findings emitted this run._").unwrap();
        writeln!(s).unwrap();
    }

    writeln!(s, "## Where to go next").unwrap();
    writeln!(s).unwrap();
    writeln!(
        s,
        "- A dimension says **Fail** or **Warn**? Open the dimension page \
         (linked above) — it has the verdict model and the implementation \
         roadmap."
    )
    .unwrap();
    writeln!(
        s,
        "- Need to fix a finding? Check [`migrations/`](migrations/) for a \
         walkthrough on this class of violation."
    )
    .unwrap();
    writeln!(
        s,
        "- Want history? Every run's structured JSON is at \
         `arena-tests/reports/history.jsonl`. This file is append-only."
    )
    .unwrap();
    writeln!(s).unwrap();

    s
}

fn verdict_glyph(v: &str) -> char {
    match v.to_ascii_lowercase().as_str() {
        "pass" => 'P',
        "warn" => 'W',
        "fail" => 'F',
        "skip" => 'S',
        "error" => 'E',
        _ => '?',
    }
}

fn titlecase(s: &str) -> String {
    let mut chars = s.chars();
    chars
        .next()
        .map(|c| c.to_ascii_uppercase().to_string() + chars.as_str())
        .unwrap_or_default()
}
